frontend:
  image: ${fe_image}
  mem_limit: 100288000
  ports:
    - "8080:8080"
  links:
    - backend
  environment:
    BACKEND_HOST: backend

backend:
  image:${be_image} 
  mem_limit: 200288000
  ports:
    - "8888:8080"
  links:
    - db
  environment:
    spring.data.mongodb.uri: mongodb://db/unicodn
    
db:
  image: tutum/mongodb:3.2
  mem_limit: 100288000
  environment:
    AUTH: 'no'
