version: '2'
services:
    frontend:
        image: rselvanathan/unicorn-frontend:latest
        ports:
            - "8080:8080"
        links:
            - backend
        environment:
            BACKEND_HOST: backend
    backend:
        image: rselvanathan/unicorn-backend:latest
        ports:
            - "8888:8080"
        links:
            - db
        environment:
            spring.data.mongodb.uri: mongodb://db/unicodn
    db:
        image: tutum/mongodb:3.2
        environment:
            AUTH: 'no'
